name: Maven CI

on:
  push:
    branches: [ "main", "feat-article" ]
  pull_request:
    branches: [ "main", "feat-article" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build and Test with Maven
      run: |
        cd server
        chmod +x mvnw
        ./mvnw clean test
